version: "3"
services:
  node:
    container_name: "server22"
    build:
      # nodejs directory를 root로 사용
      context: ./server22
      # ./server22/Dockerfile을 사용해서 build
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    container_name: mymysql80 # 컨테이너 이름 설정
    ports:
      - "3306:3306" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    environment: # -e 옵션
      MYSQL_ROOT_PASSWORD: "password"  # MYSQL 패스워드 설정 옵션
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/  
